sudo: required
services:
  - docker
before_install:
  - docker build -t giacoder/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true giacoder/docker-react npm run tests-with-watch

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-705275056322"
  bucket_path: "frontend"
  on:
    branch: main

  # TRAVIS IS NOT FREE ANYMORE. Instead of travis I've added /.github/workflows/test.yml which after push starts github actions
